export const wordBanks = {
  easy: [
    { word: 'APPLE', hint: 'A common fruit' },
    { word: 'HOUSE', hint: 'A place to live' },
    { word: 'WATER', hint: 'Essential for life' },
    { word: 'MUSIC', hint: 'Sound that entertains' },
    { word: 'LIGHT', hint: 'Opposite of dark' },
    { word: 'HAPPY', hint: 'A positive emotion' },
    { word: 'PHONE', hint: 'Communication device' },
    { word: 'CHAIR', hint: 'Furniture to sit on' },
    { word: 'PAPER', hint: 'Used for writing' },
    { word: 'CLOUD', hint: 'Floats in the sky' },
    { word: 'BALL', hint: 'Round toy' },
    { word: 'BREAD', hint: 'Used for sandwiches' },
    { word: 'TIGER', hint: 'Striped animal' },
    { word: 'PLANE', hint: 'Flies in the sky' },
    { word: 'SHIRT', hint: 'Upper clothing' },
    { word: 'SPOON', hint: 'Used for eating' },
    { word: 'MOUSE', hint: 'Small rodent' },
    { word: 'TABLE', hint: 'Used for eating' },
    { word: 'SNAKE', hint: 'Legless reptile' },
    { word: 'PIZZA', hint: 'Cheesy food' },
    { word: 'GRASS', hint: 'Green plant' },
    { word: 'CLOCK', hint: 'Shows time' },
    { word: 'BEACH', hint: 'Sandy place' },
    { word: 'DRINK', hint: 'Opposite of eat' },
    { word: 'HORSE', hint: 'Fast animal' },
    { word: 'HONEY', hint: 'Made by bees' },
    { word: 'TRUCK', hint: 'Large vehicle' },
    { word: 'EARTH', hint: 'Our planet' },
    { word: 'SMILE', hint: 'Happy expression' },
    { word: 'CAMP', hint: 'Outdoor stay' },
    { word: 'MOVIE', hint: 'You watch it' },
    { word: 'SUGAR', hint: 'Sweet powder' },
    { word: 'LEMON', hint: 'Sour fruit' },
    { word: 'ONION', hint: 'Makes you cry' },
    { word: 'MANGO', hint: 'Tropical fruit' },
    { word: 'PLANT', hint: 'Needs sunlight' },
    { word: 'FISH', hint: 'Lives in water' },
    { word: 'BABY', hint: 'Young child' },
    { word: 'JUICE', hint: 'Fruit drink' },
    { word: 'ZEBRA', hint: 'Striped animal' },
    { word: 'BALLOON', hint: 'Filled with air' },
    { word: 'FLOWER', hint: 'Blooms petals' },
    { word: 'ROAD', hint: 'Vehicles move on it' },
    { word: 'KITE', hint: 'Flies with wind' },
    { word: 'BOOK', hint: 'Used for reading' },
    { word: 'STAR', hint: 'Shines at night' },
    { word: 'SOAP', hint: 'Used for washing' },
    { word: 'MILK', hint: 'White drink' },
    { word: 'DOLL', hint: 'Toy figure' },
    { word: 'BRUSH', hint: 'Used for cleaning' },
    { word: 'BOAT', hint: 'Moves on water' },
    { word: 'BUS', hint: 'Public vehicle' },
    { word: 'SUN', hint: 'Star of our system' },
    { word: 'CAT', hint: 'Pet animal' },
    { word: 'DOG', hint: 'Loyal pet' },
    { word: 'PEN', hint: 'Used for writing' },
    { word: 'HAT', hint: 'Worn on head' },
    { word: 'RING', hint: 'Circle jewelry' },
    { word: 'KEY', hint: 'Opens lock' },
    { word: 'BED', hint: 'Used for sleeping' },
    { word: 'FAN', hint: 'Gives air' },
    { word: 'RAIN', hint: 'Falling water' },
    { word: 'MOON', hint: 'Earth\'s satellite' },
    { word: 'ICE', hint: 'Frozen water' },
    { word: 'GOLD', hint: 'Precious metal' },
    { word: 'CUP', hint: 'Holds liquid' },
    { word: 'BOX', hint: 'Square container' },
    { word: 'BAG', hint: 'Used to carry items' },
    { word: 'MAP', hint: 'Shows places' },
    { word: 'CODE', hint: 'Secret message' },
    { word: 'CAR', hint: 'Four-wheel vehicle' },
    { word: 'GATE', hint: 'Entrance barrier' },
    { word: 'COW', hint: 'Farm animal' },
    { word: 'GOAT', hint: 'Horned animal' },
    { word: 'PIG', hint: 'Pink farm animal' },
    { word: 'SHOE', hint: 'Worn on feet' },
    { word: 'TREE', hint: 'Tall plant' },
    { word: 'LEAF', hint: 'Part of a plant' },
    { word: 'POT', hint: 'Cooking container' },
    { word: 'PAN', hint: 'Flat cooker' },
    { word: 'KNIFE', hint: 'Cutting tool' },
    { word: 'HILL', hint: 'Small elevation' },
    { word: 'LAMP', hint: 'Gives light' },
    { word: 'DOOR', hint: 'Entrance panel' },
    { word: 'WALL', hint: 'Divider structure' },
    { word: 'SHOP', hint: 'Place to buy' },
    { word: 'EGG', hint: 'Oval food' },
    { word: 'CORN', hint: 'Yellow crop' },
    { word: 'RICE', hint: 'Staple food' },
    { word: 'WORM', hint: 'Small creature' },
    { word: 'GLUE', hint: 'Sticky material' },
    { word: 'ROPE', hint: 'Strong cord' },
    { word: 'POND', hint: 'Small waterbody' },
    { word: 'DESK', hint: 'Work table' },
    { word: 'GIFT', hint: 'A present' },
    { word: 'NEST', hint: 'Bird home' },
    { word: 'STICK', hint: 'Piece of wood' }
  ],
  medium: [
    { word: 'BUTTERFLY', hint: 'Colorful insect' },
    { word: 'COMPUTER', hint: 'Electronic device' },
    { word: 'MOUNTAIN', hint: 'High landform' },
    { word: 'HOSPITAL', hint: 'Medical facility' },
    { word: 'ELEPHANT', hint: 'Large mammal' },
    { word: 'CALENDAR', hint: 'Tracks dates' },
    { word: 'QUESTION', hint: 'Seeks an answer' },
    { word: 'TREASURE', hint: 'Valuable items' },
    { word: 'KEYBOARD', hint: 'Input device' },
    { word: 'LANGUAGE', hint: 'Form of communication' },
    { word: 'LIBRARY', hint: 'Place with books' },
    { word: 'BATTERY', hint: 'Stores power' },
    { word: 'COMPASS', hint: 'Shows direction' },
    { word: 'FESTIVAL', hint: 'Celebration event' },
    { word: 'PRINTER', hint: 'Prints documents' },
    { word: 'KINGDOM', hint: 'Ruled land' },
    { word: 'VOLCANO', hint: 'Erupts lava' },
    { word: 'STATION', hint: 'Transport stop' },
    { word: 'PYRAMID', hint: 'Triangular monument' },
    { word: 'CEILING', hint: 'Top of room' },
    { word: 'BLANKET', hint: 'Keeps you warm' },
    { word: 'NETWORK', hint: 'Connected system' },
    { word: 'DIAMOND', hint: 'Precious stone' },
    { word: 'PASSPORT', hint: 'Travel document' },
    { word: 'LANTERN', hint: 'Portable light' },
    { word: 'CHAMBER', hint: 'Enclosed room' },
    { word: 'HIGHWAY', hint: 'Major road' },
    { word: 'MONITOR', hint: 'Computer screen' },
    { word: 'LUGGAGE', hint: 'Travel bags' },
    { word: 'TUNNEL', hint: 'Underground path' },
    { word: 'CRYSTAL', hint: 'Clear mineral' },
    { word: 'COURAGE', hint: 'Bravery' },
    { word: 'SCULPTURE', hint: 'Carved art' },
    { word: 'WARRIOR', hint: 'Skilled fighter' },
    { word: 'CURTAIN', hint: 'Window cover' },
    { word: 'LECTURE', hint: 'Educational talk' },
    { word: 'AQUARIUM', hint: 'Fish tank' },
    { word: 'COTTAGE', hint: 'Small house' },
    { word: 'GRAVITY', hint: 'Pulling force' },
    { word: 'RECYCLE', hint: 'Reuse materials' },
    { word: 'VITAMIN', hint: 'Essential nutrient' },
    { word: 'ANTENNA', hint: 'Signal receiver' },
    { word: 'THRILLER', hint: 'Suspense story' },
    { word: 'PERFUME', hint: 'Scented liquid' },
    { word: 'STADIUM', hint: 'Sports venue' },
    { word: 'PACKAGE', hint: 'Wrapped item' },
    { word: 'PREDATOR', hint: 'Hunts prey' },
    { word: 'SURFACE', hint: 'Outer layer' },
    { word: 'ECLIPSE', hint: 'Shadow event' },
    { word: 'TURBINE', hint: 'Rotating engine' },
    { word: 'GLACIER', hint: 'Moving ice' },
    { word: 'WORKSHOP', hint: 'Training session' },
    { word: 'ARCHIVE', hint: 'Stored records' },
    { word: 'MINERAL', hint: 'Natural solid' },
    { word: 'DENSITY', hint: 'Compactness' },
    { word: 'FRICTION', hint: 'Resistance force' },
    { word: 'HABITAT', hint: 'Living environment' },
    { word: 'NUCLEUS', hint: 'Center part' },
    { word: 'TEXTURE', hint: 'Surface feel' },
    { word: 'FORTRESS', hint: 'Strong defense' },
    { word: 'ORCHARD', hint: 'Fruit farm' },
    { word: 'HORIZON', hint: 'Visible edge' },
    { word: 'SPIRAL', hint: 'Winding shape' },
    { word: 'DROUGHT', hint: 'Lack of rain' },
    { word: 'EMBASSY', hint: 'Diplomatic office' },
    { word: 'CIRCUIT', hint: 'Closed path' },
    { word: 'HYBRID', hint: 'Mixed type' },
    { word: 'LAGOON', hint: 'Shallow water' },
    { word: 'MEADOW', hint: 'Open field' },
    { word: 'ORBIT', hint: 'Circular path' },
    { word: 'RADIUS', hint: 'Half diameter' },
    { word: 'FURNACE', hint: 'Heating device' },
    { word: 'POLLEN', hint: 'Flower dust' },
    { word: 'REMEDY', hint: 'Cure method' },
    { word: 'SEGMENT', hint: 'Part of whole' },
    { word: 'TRANSIT', hint: 'Movement' },
    { word: 'TETHER', hint: 'Restraining rope' },
    { word: 'DYNASTY', hint: 'Family rule' },
    { word: 'DRIZZLE', hint: 'Light rain' },
    { word: 'GARMENT', hint: 'Clothing item' },
    { word: 'SERMON', hint: 'Religious speech' },
    { word: 'CANYON', hint: 'Deep valley' },
    { word: 'HARBOR', hint: 'Ship docking place' },
    { word: 'MARBLE', hint: 'Smooth stone' },
    { word: 'NECTAR', hint: 'Sweet liquid' },
    { word: 'POULTRY', hint: 'Farm birds' },
    { word: 'TIMBER', hint: 'Processed wood' },
    { word: 'VACUUM', hint: 'Empty space' },
    { word: 'VERDICT', hint: 'Final judgment' },
    { word: 'WILLOW', hint: 'Flexible tree' },
    { word: 'VOYAGE', hint: 'Long journey' }
  ],
  hard: [
    { word: 'ACHIEVEMENT', hint: 'Accomplishment' },
    { word: 'PSYCHOLOGY', hint: 'Study of mind' },
    { word: 'PHILOSOPHY', hint: 'Study of wisdom' },
    { word: 'ATMOSPHERE', hint: 'Layer of gases' },
    { word: 'TECHNOLOGY', hint: 'Modern innovation' },
    { word: 'INCREDIBLE', hint: 'Hard to believe' },
    { word: 'THROUGHOUT', hint: 'From start to end' },
    { word: 'VOCABULARY', hint: 'Collection of words' },
    { word: 'MYSTERIOUS', hint: 'Full of mystery' },
    { word: 'BENEFICIAL', hint: 'Providing advantage' },
    { word: 'PHOTOSYNTHESIS', hint: 'Plant energy process' },
    { word: 'BIOLUMINESCENCE', hint: 'Organisms glowing' },
    { word: 'METAMORPHOSIS', hint: 'Transformation' },
    { word: 'HALLUCINATION', hint: 'False perception' },
    { word: 'TRANSCRIPTION', hint: 'DNA copying process' },
    { word: 'CONSTELLATION', hint: 'Star grouping' },
    { word: 'SYNCHRONIZATION', hint: 'Same timing' },
    { word: 'GEOTHERMAL', hint: 'Earth heat' },
    { word: 'CATASTROPHIC', hint: 'Disastrous event' },
    { word: 'FERMENTATION', hint: 'Chemical breakdown' },
    { word: 'CONDUCTIVITY', hint: 'Energy flow ability' },
    { word: 'DIFFRACTION', hint: 'Light bending' },
    { word: 'EQUILIBRIUM', hint: 'Balanced state' },
    { word: 'PRECIPITATION', hint: 'Rainfall process' },
    { word: 'PHOTOVOLTAIC', hint: 'Solar energy' },
    { word: 'NEUROTRANSMITTER', hint: 'Brain chemical' },
    { word: 'JURISPRUDENCE', hint: 'Legal theory' },
    { word: 'SUPERSTITIOUS', hint: 'Belief in luck' },
    { word: 'BIOTECHNOLOGY', hint: 'Bio-based innovation' },
    { word: 'QUANTIFICATION', hint: 'Making measurable' },
    { word: 'BIODEGRADABLE', hint: 'Breaks naturally' },
    { word: 'TRIANGULATION', hint: 'Three-point method' },
    { word: 'LEXICALIZATION', hint: 'Word formation' },
    { word: 'DECIPHERABLE', hint: 'Can be decoded' },
    { word: 'HYPERSENSITIVE', hint: 'Over reactive' },
    { word: 'PERPENDICULAR', hint: '90-degree angle' },
    { word: 'PERSEVERANCE', hint: 'Continued effort' },
    { word: 'PROLIFERATION', hint: 'Rapid increase' },
    { word: 'METEOROLOGIST', hint: 'Weather scientist' },
    { word: 'SUSCEPTIBILITY', hint: 'Vulnerability' },
    { word: 'VENTRILOQUISM', hint: 'Voice illusion' },
    { word: 'IRREPLACEABLE', hint: 'Cannot be replaced' },
    { word: 'MISINTERPRETATION', hint: 'Wrong understanding' },
    { word: 'INTERCONTINENTAL', hint: 'Across continents' },
    { word: 'DECENTRALIZATION', hint: 'Distributed control' },
    { word: 'INTROSPECTION', hint: 'Self-analysis' },
    { word: 'MAGNIFICATION', hint: 'Enlargement' },
    { word: 'ANTIOXIDATION', hint: 'Prevents reactive damage' },
    { word: 'MONOLITHIC', hint: 'Large and uniform' },
    { word: 'TRANSCENDENTAL', hint: 'Beyond ordinary' },
    { word: 'MICROBIOLOGY', hint: 'Study of microbes' },
    { word: 'TELECOMMUNICATIONS', hint: 'Long-distance communication' },
    { word: 'CONGLOMERATION', hint: 'Clustered group' },
    { word: 'INDISTINGUISHABLE', hint: 'Hard to tell apart' },
    { word: 'FRAGMENTATION', hint: 'Breaking apart' },
    { word: 'CHRONOLOGICAL', hint: 'Time ordered' },
    { word: 'UNCOMPROMISING', hint: 'Strict stance' },
    { word: 'MISCALCULATION', hint: 'Incorrect estimate' },
    { word: 'INCOMPATIBILITY', hint: 'Cannot work together' },
    { word: 'EXTRATERRESTRIAL', hint: 'Outside Earth' },
    { word: 'ANTHROPOLOGICAL', hint: 'Human-related study' },
    { word: 'COMPUTATIONAL', hint: 'Computer based' },
    { word: 'EVAPORATION', hint: 'Turning to vapor' },
    { word: 'SUPERSONIC', hint: 'Faster than sound' },
    { word: 'IRRECOVERABLE', hint: 'Cannot be restored' },
    { word: 'DISPROPORTIONATE', hint: 'Uneven ratio' },
    { word: 'UNFORESEEABLE', hint: 'Unpredictable' },
    { word: 'MICROPROCESSOR', hint: 'CPU chip' },
    { word: 'IMMUNIZATION', hint: 'Protection from disease' },
    { word: 'LABYRINTHINE', hint: 'Extremely complex' },
    { word: 'PREMEDITATION', hint: 'Planned action' },
    { word: 'RECONNAISSANCE', hint: 'Scouting mission' },
    { word: 'REVOLUTIONARY', hint: 'Major change' },
    { word: 'HALLUCINOGENIC', hint: 'Causes hallucinations' },
    { word: 'ATMOSPHERIC', hint: 'Air-related' },
    { word: 'ELECTRIFICATION', hint: 'Adding electricity' },
    { word: 'BIODEGRADATION', hint: 'Natural breakdown' },
    { word: 'RECONFIGURATION', hint: 'Rearrangement' },
    { word: 'TRANSPLANTATION', hint: 'Organ transfer' },
    { word: 'INTERDEPENDENT', hint: 'Mutually reliant' },
    { word: 'DEMATERIALIZED', hint: 'No physical form' },
    { word: 'DEFRAGMENTATION', hint: 'Data organizing' },
    { word: 'COUNTERPRODUCTIVE', hint: 'Backfiring effect' },
    { word: 'REDISTRIBUTION', hint: 'Spreading again' },
    { word: 'UNDERESTIMATION', hint: 'Too low guess' },
    { word: 'SENSATIONALISM', hint: 'Exaggerated reporting' },
    { word: 'POSTHUMOUSLY', hint: 'After death' },
    { word: 'STRATIFICATION', hint: 'Layered structure' },
    { word: 'PSYCHOLOGICAL', hint: 'Mind-related' },
    { word: 'REMINISCENCE', hint: 'Memory recall' },
    { word: 'THERMODYNAMIC', hint: 'Heat-energy study' },
    { word: 'COMPARTMENTALIZE', hint: 'Separate into sections' },
    { word: 'DISORIENTATION', hint: 'Loss of direction' },
    { word: 'TRANSCONTINENTAL', hint: 'Across continents' },
    { word: 'INDUSTRIALIZATION', hint: 'Industry growth' },
    { word: 'PHOTOSYNTHETIC', hint: 'Relating to plant energy' },
    { word: 'CHARACTERISTICALLY', hint: 'Typically' },
    { word: 'MISCOMMUNICATION', hint: 'Failed communication' }
  ]
};

export const scrambleWord = (word) => {
  const scramble = (str) => {
    const letters = str.split('');
    for (let i = letters.length - 1; i > 0; i--) {
      const j = Math.floor(Math.random() * (i + 1));
      [letters[i], letters[j]] = [letters[j], letters[i]];
    }
    const scrambled = letters.join('');
    return scrambled === str ? scramble(str) : scrambled;
  };
  return scramble(word);
};
